# Directional change indicator

### Import

In [1]:
import numpy as np
import pandas as pd
from pathlib import Path 
import datatable as dt

from matplotlib import pyplot as plt
from collections import defaultdict

In [2]:
filepath = Path('../../data/csv/crypto_market_data.csv')

### Get data

In [3]:
df = dt.fread(filepath).to_pandas() 
df = df.T.set_index([0, 1]).T
df = df.set_index('')
df = df.astype(float)
df.index.names = ['date']
df.head(3)

0                          USDT-USD                                \
1                             Close      High       Low      Open
date
2020-04-07 09:00:00+00:00  1.000498  1.002541  1.000122  1.001162
2020-04-07 10:00:00+00:00  1.001372  1.003510  0.999029  1.000605
2020-04-07 11:00:00+00:00  1.001356  1.003241  0.999101  1.001339

0                                           BTC-USD                            \
1                               Volume        Close         High          Low
date
2020-04-07 09:00:00+00:00          0.0  7376.598145  7376.598145  7340.555176
2020-04-07 10:00:00+00:00  574005248.0  7420.056152  7427.939453  7360.825684
2020-04-07 11:00:00+00:00   35094528.0  7370.503418  7419.238770  7370.503418

0                                                    ...   ADA-USD            \
1                                 Open       Volume  ...     Close      High
date                                                 ...
2020-04-07 09:00:00+00:00  7354.051270          0.0  ...  0.036377  0.036377
2020-04-07 10:00:00+00:00  7377.067871  268472320.0  ...  0.036766  0.036869
2020-04-07 11:00:00+00:00  7419.238770          0.0  ...  0.036246  0.036799

0                                                         BNT-USD            \
1                               Low      Open    Volume     Close      High
date
2020-04-07 09:00:00+00:00  0.036196  0.036260       0.0  0.198263  0.198263
2020-04-07 10:00:00+00:00  0.036326  0.036408  113320.0  0.199927  0.200089
2020-04-07 11:00:00+00:00  0.036246  0.036799       0.0  0.197452  0.199911

0
1                               Low      Open   Volume
date
2020-04-07 09:00:00+00:00  0.197084  0.197758      0.0
2020-04-07 10:00:00+00:00  0.198244  0.198244  64615.0
2020-04-07 11:00:00+00:00  0.197452  0.199911      0.0

[3 rows x 50 columns]

In [4]:
df_btc = df['BTC-USD']

## Class DC_transform

Goal : have everything inside a well designed class
- load the data in the __init__() method
- define a method transform() that returns a new dataframe with the detected events
    - need more work for the moment --> I wanna be sure that my detected events are ok
- define a method hmm() that learns how to detect regimes based on the Time Adjusted Return (as defined in the reference book)

In [5]:
class DC_transformer:
    
    def __init__(self, data, threshold, crop):
        self.df = data.reset_index().drop(columns='date')
        self.threshold = threshold
        
    def transform(self):
        upturn_event = True
        data = self.df['Close']
        d = self.threshold
    
        """Generates directional change events from time series.
        parameters:
            data: array or list or ...
            d: Directional Change threshold
        Returns:
            A pandas series of Directional Change Events.
        """

        p = pd.DataFrame({
            "Close": data
        })
        p["Event"] = ''
        event = 'upturn'
        ph = p['Close'][0] # highest price
        pl = ph # lowest price

        for i in range(0, len(p)):

            if event == 'upturn':
                if p['Close'][i] <= (ph * (1 - d)):
                    event = 'downturn'
                    pl = p['Close'][i]
                    p.at[i, 'Event'] = 'end downturn'
                    p.at[i + 1, 'Event'] = 'start downward os'

                else:
                    if ph < p['Close'][i]:
                        ph = p['Close'][i]
                        p.at[i, 'Event'] = 'start downturn'
                        p.at[i - 1, 'Event'] = 'end upward os'
            else:
                if p['Close'][i] >= (pl * (1 + d)):
                    event = 'upturn'
                    ph = p['Close'][i]
                    p.at[i, 'Event'] = 'end upturn'
                    p.at[i + 1, 'Event'] = 'start upward os'

                else:
                    if pl > p['Close'][i]:
                        pl = p['Close'][i]
                        p.at[i, 'Event'] = 'start upturn'
                        p.at[i - 1, 'Event'] = 'end downward os'

        return p

In [6]:
DC = DC_transformer(df_btc, 0.01, True)

In [7]:
df_btc = df_btc[['Close']].reset_index().set_index('Close').join(DC.transform().set_index('Close'), on='Close')

In [8]:
df_btc = df_btc.reset_index().set_index('date')

In [9]:
df_btc

                                  Close           Event
date
2020-04-07 09:00:00+00:00   7376.598145   end upward os
2020-04-07 10:00:00+00:00   7420.056152  start downturn
2020-04-07 11:00:00+00:00   7370.503418
2020-04-07 12:00:00+00:00   7349.172363
2020-04-07 13:00:00+00:00   7358.981445
...                                 ...             ...
2022-04-07 09:05:00+00:00  43502.988281
2022-04-07 09:05:00+00:00  43502.988281
2022-04-07 09:05:00+00:00  43502.988281
2022-04-07 09:05:00+00:00  43502.988281
2022-04-07 09:06:00+00:00  43482.363281

[17561 rows x 2 columns]

### Save features

In [10]:
filepath = Path('../csv/features_btc_ta.csv')

In [11]:
#df_btc_ta.to_csv(filepath)